name: SILShack Spring 2016

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  
future: true

timezone: America/New_York

# You betcha
gems:
  - jemoji

# Categories to exclude from the index
special-categories: 
  - "exercise"
  - "how-to"
  - "sidebar"
  - "reading"
  - "notes"
  
# Exclude Jekyll's built-in tests
exclude: [vendor]

# These can contain uppercase: they'll be lowercased in the URL
page-order:
  - syllabus
  - schedule
  - assignments
  - how-to
  - people

# Same note RE case above
python-extra-pages:
  - console
  
  
permalink: none
  
baseurl: /spring2016
url: /spring2016

python: true

course:
  title: Programming for Information Professionals
  number: INLS 560
  instructor: Prof. Elliott Hauser
  semester: Spring 2016

authors:
  elliott:
      name: Elliott Hauser
      prof: true
      gravatar: 0d0d432948d262195358f339768f1240
      website: http://www.elliotthauser.com
      github: eah13
      twitter: hauspoor
      about:  Elliott Hauser is a PhD Student in information science at UNC Chapel Hill.  He's hacking education as one of the cofounders of Trinket.io.  
  
  grant:
      name: Grant McLendon
      prof: true
      gravatar: eeb73c80c4450528bf5eac5f1dedae9e
      website: http://grantmclendon.com
      github: gerbal
      twitter: gerbal100
      about: Grant is a former student and TA who helped make this site. He's from Chapel Hil and likes playing with new technologies and getting way in over his head.
  
  tommytester:
      name: Tommy the Tester
      prof: false
      gravatar:
      website: https://www.google.com/search?q=tommy+tester&rlz=1CAACAG_enUS613US613&oq=tommy+tester&aqs=chrome..69i57j0l5.2034j0j7&sourceid=chrome&es_sm=92&ie=UTF-8
      github: tommytester
      twitter: tommytester
      about: "Tommy is our tester account.  We'll use him to scope out how to use github"
    
    
  batlopez:                    
    name: batlopez
    prof: false
    gravatar:
    website: 
    github: batlopez
    twitter: 
    about: "Nat (batlopez) is a first year MSLS student interested in digital research services."
    
  camazotz:                    
    name: camazotz
    prof: false
    gravatar:
    website: 
    github: camazotz
    twitter: 
    about: "Here's a little about camazotz"
    
  clairewlj:                    
    name: clairewlj
    prof: false
    gravatar:
    website: 
    github: clairewlj
    twitter: 
    about: "Here's a little about clairewlj"
    
  ericabrody:                    
    name: ericabrody
    prof: false
    gravatar:
    website: 
    github: ericabrody
    twitter: ericabrody
    about: "I am a library science student, focused on health information. I am dabbling in information science this semester."
    
  EternalFootman:                    
    name: Kit Krueger
    prof: false
    gravatar:
    website: 
    github: EternalFootman
    twitter: WithBroomBefore
    about: "Kit is an LS student who enjoys academic libraries as well as holding coats and snickering."
    
  gao14g:                    
    name: gao14g
    prof: false
    gravatar:
    website: 
    github: gao14g
    twitter: 
    about: "Here's a little about gao14g"
    
  hannahlwang:                    
    name: hannahlwang
    prof: false
    gravatar:
    website: 
    github: hannahlwang
    twitter: 
    about: "Hannah Wang is a second semester MSIS student at SILS."
    
  izayak:                    
    name: Ruotong Yang
    prof: false
    gravatar:
    website: 
    github: izayak
    twitter: 
    about: "Ruotong Yang is a master student in STOR department at UNC Chapel Hill."
    
  jamesma560:                    
    name: jamesma560
    prof: false
    gravatar:
    website: 
    github: jamesma560
    twitter: 
    about: "Here's a little about jamesma560"
    
  JayYang95:                    
    name: JayYang95
    prof: false
    gravatar:
    website: 
    github: JayYang95
    twitter: 
    about: "Here's a little about JayYang95"
    
  jwarrich:                    
    name: jwarrich
    prof: false
    gravatar:
    website: 
    github: jwarrich
    twitter: 
    about: "Here's a little about jwarrich"
    
  namagic:                    
    name: namagic
    prof: false
    gravatar:
    website: 
    github: namagic
    twitter: 
    about: "Here's a little about namagic"
    
  nataliele:                    
    name: nataliele
    prof: false
    gravatar:
    website: 
    github: nataliele
    twitter: 
    about: "Here's a little about nataliele"
    
  payalpn:                    
    name: Payal Patel
    prof: false
    gravatar:
    website: http://www.unc.edu/~payalpn 
    github: payalpn
    twitter: 
    about: "Payal is a junior at UNC-Chapel Hill majoring in Information Science."
    
  RhymesWithMecca:                    
    name: Becca Greenstein
    prof: false
    gravatar:
    website: 
    github: RhymesWithMecca
    twitter: RhymesWithMecca
    about: "Becca is a second-semester MSLS student in SILS.  She likes science, words, the outdoors, and helping people."
    
  ShyArmadillo8:                    
    name: ShyArmadillo8
    prof: false
    gravatar:
    website: 
    github: ShyArmadillo8
    twitter: 
    about: "Here's a little about ShyArmadillo8"
    
  touchwick:                    
    name: touchwick
    prof: false
    gravatar:
    website: 
    github: touchwick
    twitter: 
    about: "Here's a little about touchwick"
    
  tsukori:                    
    name: William Chen
    prof: false
    gravatar:
    website: 
    github: tsukori
    twitter: 
    about: "Will is a Senior Computer Science major trying to graduate and move on with his life."
    
  tyym0215:                    
    name: tyym0215
    prof: false
    gravatar:
    website: 
    github: tyym0215
    twitter: 
    about: "Here's a little about tyym0215"
    
  wagerpascal:                    
    name: Jason Wang
    prof: false
    gravatar:
    website: 
    github: wagerpascal
    twitter: 
    about: "wagerpascal claims that he goes to UNC, but the time he spends at NC State suggests otherwise."
    
  wfh1972:                    
    name: wfh1972
    prof: false
    gravatar:
    website: 
    github: wfh1972
    twitter: 
    about: "Here's a little about wfh1972"
    
  wookiemage:
    name: Colin Nickels
    prof: false
    gravatar:
    website: 
    github: wookiemage
    twitter: wookiemage
    about: "Is a first year SILS student with a focus on users, technology, and libraries"
    
  yiyangshi:                    
    name: yiyangshi
    prof: false
    gravatar:
    website: 
    github: yiyangshi
    twitter: 
    about: "Here's a little about yiyangshi"
    
    
